name: Build Lichee Nano SD image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file docker/Dockerfile --tag lichee-builder:latest

      - name: Build Docker image
        run: docker build ./docker --file docker/Dockerfile --tag lichee-builder:latest
        
      - name: Upload sdcard.img
        uses: actions/upload-artifact@v4
        with:
          name: sdcard-img
          path: sdcard.img
          retention-days: 5
